version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_cybquiz}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,lambda,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
    volumes:
      - "./volume/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
